spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 1000
      max-idle: 1000
  activiti:
    database-schema-update: true
    check-process-definitions: false
